spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/heechlog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  messages:
    basename: messages,errors
    encoding: UTF-8

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: false

server:
  port: 9000

logging:
  level:
    org.hibernate.SQL: debug

token:
  secret-key: "rTPmA9Sgk+Q1XwuJbG7E6xFFUhQpdi+al5iyPnRTK/Q="