spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/heechlog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        defaul_batch_fetch_size: 1000

server:
  port: 9000

logging:
  level:
    org.hibernate.SQL: debug
