server:
  port: 9000
#  servlet:
#    session:
#      cookie:
#        max-age: 172800

spring:
  session:
    jdbc:
      initialize-schema: always
#    timeout: 86400

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/heechlog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  messages:
    basename: messages,errors
    encoding: UTF-8

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: false

logging:
  level:
    org.hibernate.SQL: debug

token:
  secret-key: "rTPmA9Sgk+Q1XwuJbG7E6xFFUhQpdi+al5iyPnRTK/Q="